#!/usr/bin/with-contenv bash

if [ -n "${PASSWORD}" ] || [ -n "${HASHED_PASSWORD}" ]; then
    AUTH="password"
else
    AUTH="none"
    echo "starting with no password"
fi

if [ -z ${PROXY_DOMAIN+x} ]; then
    PROXY_DOMAIN_ARG=""
else
    PROXY_DOMAIN_ARG="--proxy-domain=${PROXY_DOMAIN}"
fi

install-extension beardedbear.beardedtheme
install-extension bmewburn.vscode-intelephense-client
install-extension cweijan.vscode-mysql-client2

if [ ! -f "/config/mysql" ]; then
    mysql -uroot -e "CREATE USER 'abc'@'%' IDENTIFIED BY 'paulorado'; GRANT ALL PRIVILEGES ON *.* TO 'abc'@'%' WITH GRANT OPTION;"
    touch /config/mysql
fi

exec \
    s6-setuidgid abc \
        /usr/local/bin/code-server \
            --bind-addr 0.0.0.0:8443 \
            --user-data-dir /config/data \
            --extensions-dir /config/extensions \
            --disable-telemetry \
            --auth "${AUTH}" \
            "${PROXY_DOMAIN_ARG}" \
            "${DEFAULT_WORKSPACE:-/config/workspace}"
